### ISSUE TITLE
vagrant-cloudstack plugin broken with vagrant >= 1.5

### ISSUE THREAD

**Issue by gloppasglop** [schubergphilis/vagrant-cloudstack#29]
When using cloudstack plugin with vagrant 1.5.1 I'm getting the following error stack.

```
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/config.rb:73:in `method_missing': undefined method `domain' for #<VagrantPlugins::Cloudstack::Config:0x000001025b27e8> (NoMethodError)
from /Users/christopheroux/.vagrant.d/gems/gems/vagrant-cloudstack-0.2.0/lib/vagrant-cloudstack/action/connect_cloudstack.rb:18:in `call'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/warden.rb:34:in `call'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/warden.rb:34:in `call'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builder.rb:116:in `call'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/runner.rb:69:in `block in run'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/util/busy.rb:19:in `busy'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/runner.rb:69:in `run'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/machine.rb:157:in `action'
from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/batch_action.rb:72:in `block (2 levels) in run'
```

This seems to be caused by the following Vagrant change: 
https://github.com/mitchellh/vagrant/commit/f72db0c611c4806d2075cd7edba098ce923b018a that now raises a NoMethodError for missing methods.

The `lib/vagrant-cloudstack/config.rb` file defines the `domain_id` attribute:

```
  # Domain id to launch the instance into.
  #
  # @return [String]
  attr_accessor :domain_id
```

but all files in `lib/vagrant-cloudstack/action` are calling the `domain` method instead.

So the fix could be either to rename the attribute from `domain_id` to `domain` in `config.rb` (this is what I have tested and seems to work) or replace all calls to `provider_config.domain` by `provider_config.domain_id`.

**Comment by lndbrg** [comment]
To keep the code consistent we should probably use domain_id

Care to send a patch for it? Otherwise i might circle back to this on Monday.

**Comment by gloppasglop** [comment]
I have fixed it and sent a pull reques.

**Comment by loa** [comment]
@gloppasglop: Can we close this one?
